Class {
	#name : #Scissors,
	#superclass : #Object,
	#category : #RockPaperScissorsLizardSpoke
}

{ #category : #'as yet unclassified' }
Scissors >> vs: anObject [
	^anObject vsScissors
	
	
]

{ #category : #'as yet unclassified' }
Scissors >> vsLizard [ 
	^'scissors'
	
	
]

{ #category : #'as yet unclassified' }
Scissors >> vsPaper [ 
	^'scissors'
	
	
]

{ #category : #'as yet unclassified' }
Scissors >> vsRock [ 
	^'rock'
	
	
]

{ #category : #'as yet unclassified' }
Scissors >> vsScissors [
	^'draw'
	
	
]

{ #category : #'as yet unclassified' }
Scissors >> vsSpoke [ 
	^'spoke'
	
	
]
